# -*- mode: yaml -*-
owner: kmontag
repo: upptime

assignees:
  # 
  - kmontag
  # 

sites:
  # 
  - name: "a🤖a"
    url: "$SITE_918BD19863DD6CE4AD3AA93E3DC100247BC7A81492CA4360A5C84192650AE268"
  # 
  - name: "b💻b"
    url: "$SITE_3F7BCC21BCFB5A34E6A31FDA6502FBB005CC07894A23253D274667EAD237B9F7"
  # 

status-website:
  # Adjust the base URL for serving on a standard GH pages URL.
  baseUrl: /upptime
  name: "Rift Upptime"

# Don't manage repository metadata.
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
