# -*- mode: yaml -*-
owner: kmontag
repo: upptime

assignees:
  # 
  - kmontag
  # 

sites:
  # 
  - name: "a🤖a"
    url: "$SITE_F04303F111D8764BFC1E1109D357966CFD9DCFBBC9668B037853ADA760685E2E"
  # 

status-website:
  # Adjust the base URL for serving on a standard GH pages URL.
  baseUrl: /upptime
  name: "Goat Upptime"

# Don't manage repository metadata.
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
